contact/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("contacts/", include("contacts.urls")),
    path("admin/", admin.site.urls),
]

contacts/urls.py
from django.urls import path
from contacts.views import index, detail, add, post_contact
from . import views

app_name = "contacts"
urlpatterns = [
   path('index/', index.as_view(), name='index'),
   path('form/', add.as_view(), name='form'),
   path('post_contact/', post_contact, name='post_contact'),
   path("<int:contact_id>/", detail.as_view() ,name="detail"),
]

contacts/models.py
from django.db import models

# Create your models here.
class contact(models.Model):
    id= models.AutoField(primary_key=True)
    name = models.CharField(max_length=500, blank=True, null=True)
    work = models.CharField(max_length=500, blank=True, null=True)
    

class number(models.Model):
      id= models.AutoField(primary_key=True)
      number = models.CharField(max_length=500, blank=True, null=True)
      oc_key = models.ForeignKey('contact', models.DO_NOTHING, db_column='contact_key', blank=True, null=True, related_name='number')
   

contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.views import View
from django.views import generic
from contacts.models import contact, number
from django.template import loader
from django.urls import reverse

class index(View):
    def get(self,request):
        contacts_list = contact.objects.order_by("name")[:5]
        template = loader.get_template("contacts/index.html")
        context = {
            "contacts_list": contacts_list,
        }
        return HttpResponse(template.render(context, request))
class detail(View):
    def get(self,request, contact_id):
        contact_selected = contact.objects.get(id=contact_id)
        template = loader.get_template("contacts/details.html")
        numbers = [i.number for i in contact_selected.number.all()]
        context = {
            "contact": contact_selected, 'numbers': numbers
        }
        return HttpResponse(template.render(context, request))
    
class add(View):
    def get(self, request):
        template = loader.get_template("contacts/form.html")
       
        return HttpResponse(template.render({}, request))

def post_contact(request):
        a = contact.objects.create(name=request.POST['name'], work=request.POST['work'])
        b = number.objects.create(number=request.POST['number'], oc_key=a)

        
        return HttpResponseRedirect(reverse("contacts:index"))



# Create your views here.

contacts/templates/contacts/details.html
        <li>Name : {{ contact.name }}</li>
        <li>Work : {{ contact.work }}</li>
        <li>numbers :  </li>
        <ul>
            {% for number in numbers %}
        <li>{{ number }} </li>
             {% endfor %}
        </ul>

    

contacts/templates/contacts/form.html
<form action="{% url 'contacts:post_contact'  %}" method="post">
    {% csrf_token %}
 
        <label for="Name">Name</label><br>
        <input type="text" id="name" name="name"><br>
        <label for="work">work</label><br>
        <input type="text" id="work" name="work"><br>
        <label for="number">number</label><br>
        <input type="text" id="number" name="number">
     
    <input type="submit" value="submit">
    </form>

contacts/templates/contacts/index.html
{% if contacts_list %}
    <ul>
    {% for contact in contacts_list %}
        <li><a href="/contacts/{{ contact.id }}/">{{ contact.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contacts are available.</p>
{% endif %}